export function buildDebugProtocolData() {
  const projectId = "proj-debug";
  const meetingId = "meet-debug";
  return {
    mode: "protocol",
    project: { id: projectId, name: "Debug Projekt", number: "P-2026", city: "Berlin" },
    meeting: {
      id: meetingId,
      title: "Wöchentliche Baubesprechung",
      index: 5,
      is_closed: true,
      created_at: "2026-04-01T08:00:00Z",
      updated_at: "2026-04-01T09:30:00Z",
    },
    participants: Array.from({ length: 18 }).map((_, i) => ({
      kind: "firm",
      firmId: `firm-${i + 1}`,
      firmName: `Firma ${i + 1} mit langem Namen GmbH`,
      isPresent: i % 2 === 0,
      isInDistribution: i % 3 === 0,
    })),
    tops: [
      {
        id: "t1",
        level: 1,
        displayNumber: "1",
        title: "Ein sehr langer TOP-Titel der sicher umbricht und damit die neue Zeilenlogik testet",
        longtext:
          "Langtext Zeile 1 mit reichlich Inhalt. Noch mehr Worte um sicherzugehen, dass der Umbruch funktioniert und keine Zeilen abgeschnitten werden. Zweite Zeile mit weiterem Kontext. Dritte Zeile.",
        status: "offen",
        dueDate: "2026-04-15",
        responsibleLabel: "Firma 1",
        ampelColor: "orange",
        isCarriedOver: false,
        isTouched: false,
        children: [
          {
            id: "t1.1",
            level: 2,
            displayNumber: "1.1",
            title: "Unterpunkt mit mittelgroßem Titel",
            longtext: "Kurztext ohne große Überraschungen.",
            status: "verzug",
            dueDate: "2026-04-05",
            responsibleLabel: "Firma 2",
            ampelColor: "rot",
            isCarriedOver: false,
            isTouched: false,
            children: [],
          },
        ],
      },
      {
        id: "t2",
        level: 1,
        displayNumber: "2",
        title: "Erledigt, übernommen, grau darzustellen",
        longtext: "Keine weiteren Aktionen nötig.",
        status: "erledigt",
        dueDate: "2026-03-28",
        responsibleLabel: "Firma 3",
        ampelColor: "gruen",
        isCarriedOver: true,
        isTouched: false,
        children: [],
      },
      {
        id: "t3",
        level: 1,
        displayNumber: "3",
        title: "Hidden sollte nicht erscheinen",
        longtext: "Sollte gefiltert werden.",
        status: "offen",
        dueDate: "2026-04-20",
        responsibleLabel: "Firma 4",
        ampelColor: "gruen",
        isCarriedOver: false,
        isHidden: true,
        children: [],
      },
    ],
  };
}

export function buildDebugTodoData() {
  const base = buildDebugProtocolData();
  return {
    ...base,
    mode: "todo",
    tops: [
      {
        displayNumber: "1.1",
        title: "Offener ToDo-Punkt mit langem Text für Umbruchprüfung",
        status: "offen",
        dueDate: "2026-04-12",
        ampelColor: "orange",
        responsibleLabel: "Firma 1",
      },
      {
        displayNumber: "2.3",
        title: "Verzug, muss auffallen",
        status: "verzug",
        dueDate: "2026-04-05",
        ampelColor: "rot",
        responsibleLabel: "Firma 2",
      },
      {
        displayNumber: "3.1",
        title: "Blockiert ohne Fälligkeitsdatum",
        status: "blockiert",
        dueDate: "",
        ampelColor: "blau",
        responsibleLabel: "Firma 3",
      },
      {
        displayNumber: "4.2",
        title: "Ohne Ampel (keine Fälligkeit, Status offen)",
        status: "offen",
        dueDate: "",
        ampelColor: "",
        responsibleLabel: "",
      },
    ],
  };
}

export function buildDebugToplistData() {
  const base = buildDebugProtocolData();
  return {
    ...base,
    mode: "toplist",
    tops: [
      {
        id: "l1",
        level: 1,
        displayNumber: "1",
        title: "Kapitel 1 – langer Titel zur Umbruchprüfung",
        status: "offen",
        dueDate: "2026-05-10",
        ampelColor: "orange",
        responsibleLabel: "",
        isCarriedOver: false,
        isTouched: false,
        children: [
          {
            id: "l1.1",
            level: 2,
            displayNumber: "1.1",
            title: "Unterpunkt A mit mittelmäßig langem Titel",
            status: "verzug",
            dueDate: "2026-04-05",
            ampelColor: "rot",
            responsibleLabel: "Firma A",
            isCarriedOver: false,
            isTouched: false,
            children: [
              {
                id: "l1.1.1",
                level: 3,
                displayNumber: "1.1.1",
                title: "Tiefe Ebene 3",
                status: "offen",
                dueDate: "",
                ampelColor: "",
                responsibleLabel: "",
                isCarriedOver: false,
                isTouched: false,
                children: [],
              },
            ],
          },
          {
            id: "l1.2",
            level: 2,
            displayNumber: "1.2",
            title: "Erledigt, übernommen, unverändert → grau",
            status: "erledigt",
            dueDate: "2026-03-20",
            ampelColor: "gruen",
            responsibleLabel: "Firma B",
            isCarriedOver: true,
            isTouched: false,
            children: [],
          },
        ],
      },
      {
        id: "l2",
        level: 1,
        displayNumber: "2",
        title: "Kapitel 2",
        status: "offen",
        dueDate: "",
        ampelColor: "",
        responsibleLabel: "",
        isCarriedOver: false,
        isTouched: false,
        children: [],
      },
      {
        id: "hidden",
        level: 1,
        displayNumber: "X",
        title: "Hidden sollte nicht erscheinen",
        status: "offen",
        isHidden: true,
        isCarriedOver: false,
        isTouched: false,
        children: [],
      },
    ],
  };
}
